### PR TITLE
adding py demo for RNASeq data

### PR DESCRIPTION
**Pull request by jaybee84**
requesting review from @sgosline and @allaway

### CODE REVIEW

**Comment by sgosline** [comment]
This looks great. I think the only update might be to pull from the 'public table' here: syn20449214. I'm still working to get it to work with NF2, and will need to re-add the LGG data manually.

**Comment by allaway** [comment]
Looks good, here's a few suggestions: 

"r Python and refer to the necessary docs Python" python docs link appears to be duplicated
chunk 7: i'm not sure what the "unnnamed: 0" column is, but it may be the same as age - these numbers will not be accurate because the tidy dataframe replicates the metadata values for each gene...so the average age is weighted by the number of genes per patient. Maybe just restrict this to the distinct measurements?

all plots are missing axis labels for some reason.

There's no PCA plot, but this might just be a github rendering issue.

**Comment by jaybee84** [comment]
Thanks all for the suggestions. The notebooks look prettier (and bugfree) on my browser than on github... From discussion forums it seems that Github is just not great at rendering python notebooks ...

**Comment by allaway** [comment]
thanks, feel free to merge! for the nice "knit" versions (or whatever the ipynb equivalent of knitting is called) we can share via the synapse project for the hackathon.

**Pull request merged**
